export const START_LODING_CHARASTERS: 'START_LODING_CHARASTERS' =
  'START_LODING_CHARASTERS';
export const GET_CHARASTERS: 'SET_CHARASTERS' = 'SET_CHARASTERS';
export const END_LODING_CHARASTERS: 'END_LODING_CHARASTERS' =
  'END_LODING_CHARASTERS';
